import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { once } from "node:events";
import { test } from "node:test";
import { bundleClient } from "./bundle-client.mjs";

test("bundle pull reports, push freshness, failure expiry and refresh", { timeout: 40000 }, async t => {
	const dir = await mkdtemp(join(tmpdir(), "codex-diagnostics-"));
	const root = join(dir, "project"), home = join(dir, "home"), log = join(dir, "launches");
	await mkdir(root); await mkdir(home);
	const preload = join(dir, "clock.mjs");
	await writeFile(preload, 'let delta=0;const now=Date.now;Date.now=()=>now()+delta;process.on("message",value=>{delta+=value;process.send("advanced")});');
	const client = bundleClient(root, home, { CODEX_LSP_CACHE: join(dir, "cache") }, resolve("dist/cli.js"), ["--import", pathToFileURL(preload).href]);
	t.after(async () => { await client.close(); await rm(dir, { recursive: true, force: true }); });
	const configure = mode => writeFile(join(home, "lsp-client.json"), JSON.stringify({ schemaVersion: 1, trustedWorkspaces: [root], lsp: { fake: { command: [process.execPath, resolve("test/fixtures/fake-lsp.mjs")], extensions: [".fake"], env: { CODEX_LSP_TEST_MODE: mode, CODEX_LSP_TEST_LOG: log } } } }));
	await writeFile(join(root, "main.fake"), "broken\n");
	const check = (extra = {}) => client.call("check_diagnostics", { path: "main.fake", source: "lsp", ...extra });
	await configure("pull");
	assert.equal((await check()).structuredContent.errors, 1);
	assert.match((await check({ source: "both" })).content[0].text, /pull-unchanged/);
	await writeFile(join(root, "main.fake"), "fixed\n"); assert.equal((await check()).structuredContent.errors, 0);
	await configure("rename-only");
	assert.equal((await client.call("lsp_navigation", { path: "main.fake", operation: "prepare_rename" })).structuredContent.status, "unsupported");
	assert.equal((await client.call("lsp_navigation", { path: "main.fake", operation: "hover" })).structuredContent.status, "unsupported");
	assert.equal((await check()).structuredContent.results[0].state, "complete", "unsupported capability leaves the language enabled");
	await configure("empty-unversioned");
	assert.equal((await check()).structuredContent.results[0].state, "pending");
	assert.equal((await check()).structuredContent.results[0].state, "pending", "same unversioned empty cannot become clean on a hot request");
	await configure("stale-version"); assert.equal((await check()).structuredContent.results[0].state, "pending");
	await configure("late"); await writeFile(join(root, "main.fake"), "broken\n");
	const start = performance.now(); assert.equal((await check()).structuredContent.errors, 1); assert(performance.now() - start >= 300);
	await configure("startup-fail"); assert((await check()).isError);
	const launches = async () => (await readFile(log, "utf8")).trim().split("\n").length;
	const count = await launches(); assert((await check()).isError); assert.equal(await launches(), count);
	const advanced = once(client.child, "message"); client.child.send(31000); await advanced;
	assert((await check()).isError); assert.equal(await launches(), count + 1);
	await client.call("lsp_status", { path: "main.fake", refresh: true }); assert.equal(await launches(), count + 1, "status refresh stays lazy");
	assert((await check()).isError); assert.equal(await launches(), count + 2);
	await configure("pull"); assert(!(await check()).isError, "configuration changes recover immediately");
	assert((await client.call("lsp_diagnostics", { path: "main.fake" })).isError);
});

test("bundle idle release keeps stdio alive and starts a new client", { timeout: 15000 }, async t => {
	const dir = await mkdtemp(join(tmpdir(), "codex-idle-")), root = join(dir, "project"), home = join(dir, "home"), log = join(dir, "launches");
	await mkdir(root); await mkdir(home);
	await writeFile(join(root, "a.fake"), "broken\n");
	await writeFile(join(home, "lsp-client.json"), JSON.stringify({ schemaVersion: 1, lsp: { fake: { command: [process.execPath, resolve("test/fixtures/fake-lsp.mjs")], extensions: [".fake"], env: { CODEX_LSP_TEST_LOG: log } } } }));
	const preload = join(dir, "idle.mjs");
	await writeFile(preload, 'const original=setTimeout;globalThis.setTimeout=(fn,ms,...args)=>original(fn,ms===120000?100:ms,...args);');
	const client = bundleClient(root, home, { CODEX_LSP_CACHE: join(dir, "cache") }, resolve("dist/cli.js"), ["--import", pathToFileURL(preload).href]);
	t.after(async () => { await client.close(); await rm(dir, { recursive: true, force: true }); });
	assert(!(await client.call("check_diagnostics", { path: "a.fake", source: "lsp" })).isError);
	const firstPid = Number((await readFile(log, "utf8")).trim());
	await new Promise(resolve => setTimeout(resolve, 800));
	assert.throws(() => process.kill(firstPid, 0));
	assert(!(await client.call("check_diagnostics", { path: "a.fake", source: "lsp" })).isError);
	assert.equal((await readFile(log, "utf8")).trim().split("\n").length, 2);
});
