import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, mkdir, writeFile, readFile, rm, chmod } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test } from "node:test";
import { bundleClient } from "./bundle-client.mjs";

test("bundle local priority, ecosystem launchers, failure isolation, trust and migration", { timeout: 60000, skip: process.platform === "win32" }, async t => {
	const dir = await mkdtemp(join(tmpdir(), "codex-resolution-"));
	const root = join(dir, "project"), home = join(dir, "home"), bin = join(dir, "bin"), log = join(dir, "launchers");
	await mkdir(join(root, "pkg", "src"), { recursive: true }); await mkdir(home); await mkdir(bin);
	t.after(() => rm(dir, { recursive: true, force: true }));
	const script = async (path, body) => { await mkdir(resolve(path, ".."), { recursive: true }); await writeFile(path, `#!${process.execPath}\n${body}\n`); await chmod(path, 0o755); };
	const fake = resolve("test/fixtures/fake-lsp.mjs");
	const fakeLsp = `import(${JSON.stringify(fake)});`;
	const launcher = `require("node:fs").appendFileSync(${JSON.stringify(log)},process.argv.join(" ")+"\\n");process.exit(7);`;
	for (const name of ["uvx", "uv", "pipx", "npx"]) await script(join(bin, name), launcher);
	await script(join(bin, "ty"), fakeLsp); await script(join(bin, "ruff"), 'console.log("[]")');
	await writeFile(join(root, "pkg", "src", "main.py"), "broken\n");
	const configure = async value => {
		const { workspaces = [root], ...settings } = value;
		await writeFile(join(home, "config.toml"), workspaces.map(path => `[projects.${JSON.stringify(path)}]\ntrust_level = "trusted"\n`).join("\n"));
		await writeFile(join(home, "lsp-client.json"), JSON.stringify({ schemaVersion: 1, automaticDiagnostics: { postToolUse: "off", stop: "off" }, ...settings }));
	};
	await configure({});
	const client = bundleClient(root, home, { PATH: bin, CODEX_LSP_CACHE: join(dir, "cache") });
	t.after(() => client.close());
	const status = async path => { const result = await client.call("lsp_status", { path }); assert(!result.isError, JSON.stringify(result)); return result.structuredContent.tools[0]; };
	assert.equal((await status("pkg/src/main.py")).tool.command[0], join(bin, "ty"));
	assert.equal((await status("pkg/src/main.py")).lint.command, join(bin, "ruff"));
	assert(!(await client.call("check_diagnostics", { path: "pkg/src/main.py" })).isError);
	assert.equal(await readFile(log, "utf8").catch(() => ""), "");
	for (const base of [root, join(root, "pkg")]) { await script(join(base, ".venv", "bin", "ty"), fakeLsp); await script(join(base, ".venv", "bin", "ruff"), 'console.log("[]")'); }
	assert.equal((await status("pkg/src/main.py")).tool.command[0], join(root, "pkg", ".venv", "bin", "ty"));
	assert.equal((await status("pkg/src/main.py")).lint.command, join(root, "pkg", ".venv", "bin", "ruff"));
	await client.call("check_diagnostics", { path: "pkg/src/main.py", refresh: true });
	assert.equal(await readFile(log, "utf8").catch(() => ""), "");
	await rm(join(root, "pkg", ".venv"), { recursive: true }); await rm(join(root, ".venv"), { recursive: true });
	await script(join(root, "pkg", ".venv", "bin", "ty"), fakeLsp);
	assert.equal((await status("pkg/src/main.py")).tool.source, "project");
	assert.equal((await status("pkg/src/main.py")).lint.source, "PATH");
	assert(!(await client.call("check_diagnostics", { path: "pkg/src/main.py", refresh: true })).isError);
	await rm(join(root, "pkg", ".venv"), { recursive: true });
	await script(join(root, "pkg", ".venv", "bin", "ruff"), 'console.log("[]")');
	assert.equal((await status("pkg/src/main.py")).tool.source, "PATH");
	assert.equal((await status("pkg/src/main.py")).lint.source, "project");
	assert(!(await client.call("check_diagnostics", { path: "pkg/src/main.py", refresh: true })).isError);
	await rm(join(root, "pkg", ".venv"), { recursive: true });
	await script(join(root, "node_modules", ".bin", "typescript-language-server"), fakeLsp);
	await script(join(root, "pkg", "node_modules", ".bin", "typescript-language-server"), fakeLsp);
	assert.equal((await status("pkg/src/main.ts")).tool.command[0], join(root, "pkg", "node_modules", ".bin", "typescript-language-server"));
	await configure({ lsp: { typescript: "tsc" } });
	for (const base of [root, join(root, "pkg")]) await script(join(base, "node_modules", ".bin", "tsc"), fakeLsp);
	assert.equal((await status("pkg/src/main.ts")).tool.command[0], join(root, "pkg", "node_modules", ".bin", "tsc"));
	assert.deepEqual((await status("pkg/src/main.ts")).tool.command.slice(1), ["--lsp", "--stdio"]);
	await rm(join(root, "pkg", "node_modules", ".bin", "tsc"));
	assert.equal((await status("pkg/src/main.ts")).tool.command[0], join(root, "node_modules", ".bin", "tsc"));
	await writeFile(join(root, "pkg", "src", "main.ts"), "export const value = 1;\n");
	await script(join(root, "node_modules", ".bin", "tsc"), 'console.error("old tsc does not support --lsp");process.exit(9)');
	const oldTsc = await client.call("check_diagnostics", { path: "pkg/src/main.ts", source: "lsp" });
	assert(oldTsc.isError); assert.match(oldTsc.content[0].text, /no fallback/);
	assert.equal(await readFile(log, "utf8").catch(() => ""), "", "incompatible local tsc must not launch npx");
	await configure({ lsp: { typescript: "tsgo" } });
	await script(join(bin, "tsgo"), fakeLsp);
	assert.equal((await status("pkg/src/main.ts")).tool.source, "PATH");
	assert.deepEqual((await status("pkg/src/main.ts")).tool.command.slice(1), ["--lsp", "--stdio"]);
	await rm(join(bin, "tsgo")); assert.equal((await status("pkg/src/main.ts")).tool.source, "missing");
	await configure({});
	await rm(join(root, "node_modules"), { recursive: true }); await rm(join(root, "pkg", "node_modules"), { recursive: true });
	assert.equal(await readFile(log, "utf8").catch(() => ""), "");
	const localFailures = join(dir, "local-failures");
	await script(join(root, "healthy", ".venv", "bin", "ty"), fakeLsp);
	await writeFile(join(root, "healthy", "main.py"), "broken\n");
	await script(join(bin, "ty"), `require("node:fs").appendFileSync(${JSON.stringify(localFailures)}, "started\\n");console.error("broken local toolchain");process.exit(9)`);
	const broken = await client.call("check_diagnostics", { path: "pkg/src/main.py", refresh: true });
	assert.equal(broken.structuredContent.results[0].channels.lsp, "failed"); assert.match(broken.content[0].text, /no fallback/);
	assert(!(await client.call("check_diagnostics", { path: "healthy/main.py", source: "lsp" })).isError);
	assert((await client.call("check_diagnostics", { path: "pkg/src/main.py", source: "lsp" })).isError);
	assert.equal(await readFile(localFailures, "utf8"), "started\n", "a healthy package must not clear another package's failure cache");
	assert.equal(await readFile(log, "utf8").catch(() => ""), "");
	await rm(join(bin, "ty"));
	for (const expected of ["uvx", "uv", "pipx"]) {
		assert.equal((await status("pkg/src/main.py")).tool.command[0], join(bin, expected));
		assert.equal((await status("pkg/src/main.c")).tool.source, "missing");
		await rm(join(bin, expected));
	}
	assert.equal((await status("pkg/src/main.py")).tool.source, "missing");
	assert.equal((await status("pkg/src/main.ts")).tool.command[0], join(bin, "npx"));
	assert((await status("pkg/src/main.ts")).tool.command.includes("typescript@5.9.3"));
	await configure({ lsp: { typescript: "tsc" } });
	assert((await status("pkg/src/main.ts")).tool.command.includes("typescript@7.0.2"));
	assert.deepEqual((await status("pkg/src/main.ts")).tool.command.slice(-3), ["tsc", "--lsp", "--stdio"]);
	await configure({});
	await rm(join(bin, "npx")); assert.equal((await status("pkg/src/main.ts")).tool.source, "missing");
	await script(join(bin, "ty"), fakeLsp); await rm(join(bin, "ruff"));
	assert(!(await client.call("check_diagnostics", { path: "pkg/src/main.py", source: "lsp", refresh: true })).isError);
	const noRuff = await client.call("check_diagnostics", { path: "pkg/src/main.py" });
	assert(!noRuff.isError); assert.equal(noRuff.structuredContent.results[0].channels.lsp, "complete");
	assert.equal(noRuff.structuredContent.results[0].channels.lint, "failed");
	assert(!(await client.call("lsp_navigation", { path: "pkg/src/main.py", operation: "definition", line: 1, column: 1 })).isError);
	const second = join(dir, "second"); await mkdir(second);
	await configure({ workspaces: [root, second], lsp: { python: false, rust: false, fake: { command: [process.execPath, fake], extensions: [".fake"] } } });
	await writeFile(join(root, "main.fake"), "broken\n"); await writeFile(join(second, "main.fake"), "clean\n");
	await writeFile(join(root, "unavailable.rs"), "fn main() {}\n"); await writeFile(join(root, "note.txt"), "ordinary text\n");
	const mixed = await client.call("check_diagnostics", { paths: ["main.fake", "unavailable.rs"], source: "lsp" });
	assert(!mixed.isError); assert(mixed.structuredContent.partial); assert(mixed.structuredContent.unavailable.rust);
	assert(!mixed.structuredContent.results.some(entry => entry.path === "note.txt"));
	assert.equal((await client.call("check_diagnostics", { workspace: second, path: "main.fake", source: "lsp" })).structuredContent.errors, 0);
	assert.equal((await client.call("check_diagnostics", { path: "main.fake", source: "lsp" })).structuredContent.errors, 1);
	assert((await client.call("lsp_format", { paths: ["main.fake", "unavailable.rs"] })).isError);
	assert.equal(await readFile(join(root, "main.fake"), "utf8"), "broken\n", "failed preflight prevents all writes");
	const longPaths = Array.from({ length: 60 }, (_, index) => `${index}-${"x".repeat(150)}.fake`);
	await Promise.all(longPaths.map(path => writeFile(join(root, path), "broken\n")));
	const longWrite = await client.call("lsp_format", { paths: longPaths });
	assert(!longWrite.isError, JSON.stringify(longWrite));
	assert(longWrite.content[0].text.length <= 8000);
	assert.deepEqual(longWrite.structuredContent.modifiedPaths, longPaths.sort(), "structured writes retain every path after text truncation");
	await Promise.all(longPaths.map(path => rm(join(root, path))));
	await configure({ lsp: { python: false } });
	assert((await client.call("check_diagnostics", { path: "pkg/src/main.py" })).isError);
	await mkdir(join(root, ".codex")); await writeFile(join(root, ".codex", "lsp-client.json"), "invalid project json");
	await configure({ workspaces: [] }); assert(!(await client.call("lsp_status")).isError);
	await configure({}); assert((await client.call("lsp_status")).isError);
	await rm(join(root, ".codex"), { recursive: true });
	await writeFile(join(home, "lsp-client.json"), "{}");
	assert.match((await client.call("lsp_status")).content[0].text, /Migration required/);
	const hook = spawnSync(process.execPath, [resolve("dist/cli.js"), "hook"], { cwd: root, env: { ...process.env, CODEX_HOME: home, PATH: bin, CODEX_LSP_CACHE: join(dir, "cache"), LSP_TOOLS_MCP_USER_CONFIG: "obsolete" }, input: JSON.stringify({ cwd: root, session_id: "s", hook_event_name: "SessionEnd" }), encoding: "utf8" });
	assert.equal(hook.status, 0); assert.equal(hook.stdout, "", "cleanup survives configuration errors");
});
