import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test } from "node:test";
import { bundleClient } from "./bundle-client.mjs";

test("native TypeScript 7 through delivered MCP: diagnostics, navigation, rename and format", { timeout: 60000 }, async t => {
	const dir = await mkdtemp(join(tmpdir(), "codex-tsc-"));
	const root = join(dir, "project"), home = join(dir, "home");
	await mkdir(root); await mkdir(home);
	await symlink(resolve("node_modules"), join(root, "node_modules"), process.platform === "win32" ? "junction" : "dir");
	await writeFile(join(home, "lsp-client.json"), JSON.stringify({ schemaVersion: 1, trustedWorkspaces: [root], lsp: { typescript: "tsc" }, lint: { javascript: "off" } }));
	await writeFile(join(root, "tsconfig.json"), JSON.stringify({ compilerOptions: { strict: true, noEmit: true, target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", types: [] }, include: ["*.ts"] }));
	const defs = 'export interface Shape { value: number; }\nexport function greet(name: string): string { return name; }\n';
	const main = type => `import { greet, type Shape } from "./defs.js";\nexport const answer: ${type} = greet("world");\nexport const shape: Shape = { value: 1 };\n`;
	await writeFile(join(root, "defs.ts"), defs);
	await writeFile(join(root, "main.ts"), main("number"));
	const client = bundleClient(root, home);
	t.after(async () => { await client.close(); await rm(dir, { recursive: true, force: true }); });
	const call = async (name, args) => { const result = await client.call(name, args); assert(!result.isError, JSON.stringify(result)); return result; };
	const check = async () => {
		const result = (await call("check_diagnostics", { path: "main.ts", source: "lsp" })).structuredContent;
		assert.equal(result.results[0].state, "complete", JSON.stringify(result));
		return result;
	};
	const status = (await call("lsp_status", { path: "main.ts" })).structuredContent.tools[0];
	assert.equal(status.tool.source, "project"); assert.deepEqual(status.tool.command.slice(1), ["--lsp", "--stdio"]);
	assert.equal(status.running, false, "status must not start the native server");
	const broken = await check(); assert.equal(broken.errors, 1); assert.match(JSON.stringify(broken.results), /2322/);
	await writeFile(join(root, "main.ts"), main("string"));
	assert.equal((await check()).errors, 0);
	const nav = async (operation, path = "main.ts", line = 2, column = main("string").split("\n")[1].indexOf("greet") + 1) => JSON.parse((await call("lsp_navigation", { path, operation, line, column })).content[0].text);
	assert.match(JSON.stringify(await nav("definition")), /defs\.ts/);
	assert.match(JSON.stringify(await nav("references")), /main\.ts/);
	assert((await nav("hover")).contents);
	assert((await nav("symbols", "defs.ts", 1, 1)).length > 0);
	assert((await nav("prepare_rename")).range);
	assert((await nav("signatureHelp", "main.ts", 2, main("string").split("\n")[1].indexOf('"world"') + 1)).signatures.length > 0);
	assert.match(JSON.stringify(await nav("typeDefinition", "main.ts", 3, 14)), /defs\.ts/);
	assert(Array.isArray(await nav("implementation", "defs.ts", 1, 18)));
	await writeFile(join(root, "defs.ts"), defs.replace(": string { return name; }", ": number { return name.length; }"));
	assert.equal((await check()).errors, 1, "dependency changes invalidate clean native diagnostics");
	await writeFile(join(root, "defs.ts"), defs); assert.equal((await check()).errors, 0);
	const rename = await call("lsp_rename", { path: "defs.ts", line: 2, column: 18, newName: "welcome" });
	assert.deepEqual(rename.structuredContent.modifiedPaths.sort(), ["defs.ts", "main.ts"]);
	assert.match(await readFile(join(root, "main.ts"), "utf8"), /welcome\("world"\)/);
	assert.match(await readFile(join(root, "defs.ts"), "utf8"), /function welcome/);
	await writeFile(join(root, "format.ts"), "export function twice(value:number){return value*2;}\n");
	await call("lsp_format", { path: "format.ts" });
	assert.match(await readFile(join(root, "format.ts"), "utf8"), /value: number/);
	assert.match(await readFile(join(root, "format.ts"), "utf8"), /value \* 2/);
	assert.equal((await check()).errors, 0);
	assert.equal((await call("lsp_status", { path: "main.ts" })).structuredContent.tools[0].running, true);
});
